name: Build and Deploy Client

on:
  push:
    branches:
      - master
    paths:
      - 'todo-client/**'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku auth:token

      - name: Set Heroku Config Vars
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_CLIENT_APP_NAME: ${{ secrets.HEROKU_CLIENT_APP_NAME }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
        run: |
            heroku config:set NPM_CONFIG_PRODUCTION=false VITE_API_URL=$VITE_API_URL VITE_APP_ID=$VITE_APP_ID VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY VITE_MEASUREMENT_ID=$VITE_MEASUREMENT_ID VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID VITE_PROJECT_ID=$VITE_PROJECT_ID VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET --app $HEROKU_CLIENT_APP_NAME

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./todo-client

      - name: Build client
        run: npm run build
        working-directory: ./todo-client

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_CLIENT_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: todo-client




      